# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200120_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u0443')),
                ('data_and_time', models.DateTimeField(null=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('teacher', models.CharField(max_length=256, verbose_name='\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447')),
                ('examenation', models.ManyToManyField(blank=True, max_length=256, null=True, to='students.Group', verbose_name='\u0421\u043a\u043b\u0430\u0434\u0430\u044e\u0442\u044c \u0456\u0441\u043f\u0438\u0442')),
            ],
            options={
                'verbose_name': '\u0406\u0441\u043f\u0438\u0442',
                'verbose_name_plural': '\u0406\u0441\u043f\u0438\u0442\u0438',
            },
        ),
    ]
