# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200204_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examenation',
            field=models.ManyToManyField(blank=True, max_length=256, to='students.Group', verbose_name='\u0421\u043a\u043b\u0430\u0434\u0430\u044e\u0442\u044c \u0456\u0441\u043f\u0438\u0442'),
        ),
    ]
