# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200204_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='title',
            new_name='subject',
        ),
    ]
